// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yrubwjtitmmkoqetguja.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlydWJ3anRpdG1ta29xZXRndWphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3MTg2MDIsImV4cCI6MjA2NjI5NDYwMn0.egYDW-d4KKR1AkHVyPMQ5b2CSmYG3t_qhU1uG-XK1Uo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);